stfc/cloud-capi-values

flavors.yaml

In the previous commit, this was changed because the 8GB + 50GB RAM/Disk respectively made it a bit tight for most workloads. I was meant to go one step up (tiny @ 16/100), but instead went to small which is 128GB RAM per machine.
This meant, to deploy a cluster, the user would need 0.5TB of RAM...let's adjust it back to something sensible

Correct default flavor size

---

values.yaml

This enables deploying the Monitoring stack by default. This includes Loki which will allow us to forward stdout/err onto our centralised logging.
By default the stack will deploy with a ClusterIP configuration, so will not be available outside the cluster (except for using kubectl port-forward) unless the user explicitly makes it available.

Enable Monitoring by default

---

values.yaml

Removes an empty global block which effectively nulled out the section from upstream, including imagePrefix.
This would result in the following error attempting to upgrade: 
```Error: template: openstack-cluster/templates/autoscaler/deployment.yaml:26:20: executing "openstack-cluster/templates/autoscaler/deployment.yaml" at <include "openstack-cluster.autoscaler.image" .>: error calling include: template: openstack-cluster/templates/_helpers.tpl:156:64: executing "openstack-cluster.autoscaler.image" at <.Values.global.imagePrefix>: nil pointer evaluating interface {}.imagePrefix```

Remove null 'global' block

---

values.yaml

Upstream sets nova by default for Cinder CSI storage class. 
`values.yaml` has been updated to override the default availability zone and force a different availability zone to be used.

Force availability zone to not use default for Cinder storage class

---

flavors.yaml
user-values.yaml

- Bump the version to the latest public image :tada: 
- Rejig the default counts of machine based on ops feedback and experience

K8s 1_27 image bump

---

user-values.yaml

Adds the config for the ingress controller, this will steer users to not allocate a FIP per service, makes TLS trivial (using certbot or similar) and avoids duplicating effort because we use the StackHPC charts.
This disabled by default, pending documentation and additional testing. But I want to ensure the correct values is captured whilst we're here.
---
To test:
- Deploy with this config
- Uninstall the cluster
- Set ingress to enabled, and set a FIP (one already in your project) in `user-values.yaml`, re deploy and check the LB comes up with said IP

Add ingress controller, disabled by default

---

values.yaml

There was a typo in values.yaml which meant ceph was not set as the default availability zone for the cinder-csi

BUG: Set storageclass to use ceph

---

bootstrap.sh

Adds a bootstrap script which preps the local VM (assuming Ubuntu) to:
- Update local packages
- Check for clouds.yaml
- Automatically populate the project ID
- Snap provision microk8s
- Install and init the clusterctl OpenStack components
- Install a specified version of add-ons
This should streamline the provisioning steps significantly, and reduce the various errors we were seeing from doc steps being missed

ENH: Add bootstrap script

---

values.yaml

Addresses some points flagged for improvement for our default values:
- DNS should be picked up through the DHCP allocation on the VM
- The services and pod nets overlap, this could cause problems so segment it into two /13 addresses

MAINT: Address feedback on values

---

bootstrap.sh

also added new line to account for the fact the new CAPO version is currently not working.

Move to new CAPI version (v1.7.0)

---

bootstrap.sh

There's a 1.7.1 release, bump the minor version so users get the latest version

MAINT: Bump minor version for clusterctl

---

bootstrap.sh

since we should only have one external network anyway - we should just remove this so it will work better with cloud-deployed-apps

MAINT: remove getting external network id

---

user-values.yaml

There is an issue in argocd where it is expecting different things than what the defaults are
So just add this as a quick fix

BUG: fixes issue with argocd OutofSync issues

---

bootstrap.sh

Update cluster-api-addon-provider chart version to 0.5.6 in the bootstrap script

MAINT: Update CAPI addon provider chart version

---

bootstrap.sh

These are part of regular updates. This should also fix the various crash-loops we've seen with the pod recently

Bump CAPO to v0.10.4, and clusterctl to v1.7.4

---

bootstrap.sh

Updated a line in the bootstrap script to download the newest version of CAPI (v1.8.1) after testing.

Updated CAPI to newest version. (v1.8.1)

---

values.yaml

running into issues where we run out of IPs for large clusters like jupyterhub.
since we provide a fully private network space for k8s we should be fine going to /16
we cap most users at 500 ports so it shouldn't cause issue to enable for everyone
NOTE: This does need to be tested - worth using this branch to spin up JupyterHub next time we need to.

MAINT: increase IP range

---

flavors.yaml

The default is dangerous as it can affect the cluster if it's running something like Longhorn and deletes all the nodes underneath it. Reduce the maxUnhealthy down to delete 1/5th at a time

BUG: Reduce max unhealthy percentage

---

bootstrap.sh
dependencies.json

having a separate dependencies file makes it easier for us to update versions and potentially use dependabot or something similar for this repo

ENH: setup dependencies.json

---

bootstrap.sh

After #31 it looks like the script is broken due to the env variables being set in outside of the main process, from the quick google it looks this is because of the variables being set in the sub processor and not in the main one. I am not very good with bash but I have changed the while loop a bit, and it looks like it works.
This is the error I had before my change: 
The script can be tested by adding echo on line 32 and commenting out everything below it. Without the change it will produce an unbound error, with the change it will correctly echo the version

Rework the while loop to not start it as a sub process

---

flavors.yaml

For nodeGroups the name of the group cannot contain `_` or `.` otherwise the cluster will not recognise the node and won't add the new machines to the cluster. Added a note to the `flavors.yaml` file

DOC: Add note about valid names for nodeGroups

---

values.yaml

Upstream points to `ghcr.io`, `quay.io` etc using their own mirror which may cause issues with private containers. Setting the values for registry mirrors to `null` to not have a mirror for the registry.

BUG: Fix issue with registry mirror
